config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  resources :feeds do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    validates :content, presence: true, if: -> { image.blank? }
    validates :content,length:   { in:1..140 }
    validates :image, presence: true, if: -> { content.blank? }
    
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length:{ maximum:100}
    after_initialize do |movie|
      puts "オブジェクトは初期化されました"
    end
  
end

app/models/user.rb
    class User < ApplicationRecord
        has_many :favorites, dependent: :destroy
        has_many :blogs
        has_many :feeds
        validates :name,  presence: true, length: { maximum: 30 }
        validates :email, presence: true, length: { maximum: 255 },
                          format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
        before_validation { email.downcase! }
        has_secure_password
        validates :password, length: { minimum: 6 }
       
    end
    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    before_action :login_required

    private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: %i[ show edit update destroy ]
  before_action :access,only: %i[edit destroy]

  # GET /feeds or /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1 or /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end
  def confirm
    @feed = current_user.feeds.build(feed_params)
    render :new  if @feed.invalid?
  end
  
  def edit
    @feed = Feed.find(params[:id])
  end

  def create
    @feed = current_user.feeds.build(feed_params)
      if params[:back]
        render :new
      else

      respond_to do |format|
        if @feed.save
          format.html { redirect_to feed_url(@feed), notice: "Feed was successfully created." }
          format.json { render :show, status: :created, location: @feed }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @feed.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /feeds/1 or /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to feed_url(@feed), notice: "Feed was successfully updated." }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1 or /feeds/1.json
  def destroy
    @feed.destroy
      respond_to do |format|
      format.html { redirect_to feeds_url, notice: "Feed was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
  def set_feed
    @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:image,:image_cache,:content)
  end

  def access
   unless @current_user.id && @feed.user.id == @current_user.id
   flash[:notice] = "権限がありません"
   redirect_to feeds_path
  end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]  
    def new
      @user = User.new
    end
      
    def create
      @user = User.new(user_params)
        if @user.save
          redirect_to user_path(@user.id)
        else
          render :new
        end
    end
      
    def show
      @user = User.find(params[:id])
    end
      
    private 
    def user_params
      params.require(:user).permit(:name, :email, :password,:password_confirmation)
    end
end      

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_feeds_path
    elsif action_name == 'edit' #編集画面の場合は、確認画面が不要だから
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
  
  def choose_new
    if action_name == 'new' 
      sessions_path
    end
  end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
  <%= form_with(model: @feed, local: true,url:choose_new_or_edit) do |form| %>
  <div class="field">
    <strong><%= form.label :image %></strong>
      <br>
        <%= image_tag (@feed.image.url), size: '320x240' if @feed.image && @feed.image.url%>
        <%= form.file_field :image %>
        <%= form.hidden_field :image_cache %>
      <br>
      <br>
    <div class="field">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to "一覧画面にもどる", feeds_path %>

app/views/feeds/confirm.html.erb
<h2>確認画面</h2>
  <%= form_with(model: @feed, local: true) do |form| %>
    <%= image_tag (@feed.image.url), size: '320x240' if @feed.image && @feed.image.url%>
    <p class="abc"><strong>内容: <%= @feed.content %></strong></p> 
    <%= form.hidden_field :content %>
    <br>
    <br>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "投稿する" %>
  <% end %>
    <%= link_to "投稿画面に戻る", new_feed_path%>
<br>

app/views/feeds/edit.html.erb
<h2>編集画面</h2>
<%= render 'form', feed: @feed %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Feeds</h1>
<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.image %></td>
        <td><%= image_tag (feed.image.url), size: '320x240' if feed.image && feed.image.url%></td>
        <td><%= feed.user.name %>が投稿 </td>
        <td><%= feed.content %>内容 </td>
        <td><%= link_to 'Show', feed %></td>

         <% if  current_user.id == feed.user.id%> 
        <td><%= link_to 'Edit', edit_feed_path(feed.id)%></td>
        <td><%= button_to 'Destroy',feed_path(feed.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>
<%= render 'form', feed: @feed %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <br>
  <%= image_tag (@feed.image.url), size: '320x240' if @feed.image && @feed.image.url%>
</p>
<p class="abc">内容: <%= @feed.content %></p>
<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="masthead" style="background-image: url(<%= asset_path 'home-bg.jpg' %>)">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1 style="text-align:center;"> Friend</h1>
                </div>
            </div>
        </div>
    </div>
</header>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  <body>
   <div class="main-container"style="background-image: url(<%= asset_path 'home-bg.jpg' %>)">
   <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal" ><a href="/feeds/">ユーザ・画像一覧</a></h5>
      <nav class="my-2 my-md-0 mr-md-3">
      </nav>

      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

    <% if logged_in? %>
      <%= link_to "Profile ", user_path(current_user.id) %> |
      <%= button_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %> |
      <%= link_to "Login", new_session_path %>
    <% end %>
    </div> 
    <p class="alert"><%= alert %></p>
    <div class="test">
    <%= yield %>
    </div>
    </div>
  </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<div>
  <a class="p-2 text-dark" href="/feeds/">ユーザー画像一覧へ</a>
</div> 
<p>メールアドレス: <%= @user.email %></p>